# Generated by Django 4.2.2 on 2023-07-09 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cybersec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('ip_address', models.TextField(default='', max_length=50, null=True)),
                ('device_type', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('port_info', models.TextField(max_length=10, null=True)),
                ('auth_credintials', models.TextField(max_length=255, null=True)),
                ('scan_preferces', models.TextField(max_length=255, null=True)),
                ('scan_schudule', models.TextField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersec.user')),
            ],
        ),
    ]
