# Generated by Django 4.2.2 on 2023-07-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybersec', '0004_rename_groups_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
